title: Wash
# TODO: Update google_analytics
google_analytics: UA-144580607-1
exclude: [vendor, Boltdir, acceptance, modules, .git, Gemfile, Gemfile.lock]

collections:
  tutorials:
    output: true

defaults:
  - scope:
      type: tutorials
    values:
      layout: tutorial
  - scope:
      type: posts
    values:
      layout: post
      permalink: /:categories/:year-:month-:day-:title

plugins:
  - jekyll-feed
